# Generated by Django 5.0.4 on 2024-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('tin', models.CharField(max_length=11, unique=True)),
                ('pin', models.CharField(max_length=9)),
                ('cell', models.CharField(max_length=14)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
